name: Actualizar Datos de GDELT sobre Escándalos

on:
  schedule:
    - cron: '0 1 * * *'  # Ejecutar una vez al día a la 01:00 AM (UTC)
  workflow_dispatch:       # Permite la ejecución manual

jobs:
  update-gdelt-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create data directory
        run: |
          mkdir -p data

      - name: Run GDELT data script
        run: python scripts/gdelt_scandal_data.py

      - name: Commit and push new JSON data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/data_gdelt.json
          git commit -m "chore: Update GDELT scandal data" || echo "No changes to commit"
          git push
