# scripts/update_cultural_data.yml
name: Actualizar Datos Culturales WVS

description: |
  Script para actualizar mensualmente los datos culturales del World Values Survey

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'  # Ejecutar el día 1 de cada mes a las 2:00 AM
  push:
    branches: [ main ]
    paths:
      - 'scripts/update_cultural_data.py'

jobs:
  actualizar-datos-culturales:
    name: Actualizar Datos Culturales
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy beautifulsoup4 lxml

    - name: Verificar instalación de dependencias
      run: |
        echo "Dependencias instaladas:"
        pip list | grep -E "requests|pandas|numpy|beautifulsoup4|lxml"
        echo ""
        echo "Verificando importaciones:"
        python -c "import requests; import pandas; import numpy; from bs4 import BeautifulSoup; print('✅ Todas las dependencias importadas correctamente')"

    - name: Crear directorio de datos
      run: |
        mkdir -p data
        echo "Directorio data creado"

    - name: Ejecutar script de actualización cultural
      run: |
        python scripts/update_cultural_data.py
      env:
        PYTHONPATH: ${{ github.workspace }}
      timeout-minutes: 30

    - name: Verificar archivo generado
      run: |
        if [ -f "data/data_worldsurvey_valores.json" ]; then
          echo "✅ Archivo cultural generado correctamente"
          ls -la data/data_worldsurvey_valores.json
          echo "Tamaño del archivo: $(du -h data/data_worldsurvey_valores.json | cut -f1)"
          echo "Estructura del archivo:"
          python -c "
          import json
          try:
              with open('data/data_worldsurvey_valores.json', 'r') as f:
                  data = json.load(f)
              print(f'Países procesados: {len(data.get(\"countries\", {}))}')
              print(f'Fecha generación: {data.get(\"metadata\", {}).get(\"processing_date\")}')
              print(f'Fuente: {data.get(\"metadata\", {}).get(\"source\")}')
          except Exception as e:
              print(f'Error leyendo JSON: {e}')
          "
        else
          echo "❌ Error: No se generó el archivo cultural"
          exit 1
        fi

    - name: Subir artefacto con datos culturales
      uses: actions/upload-artifact@v4
      with:
        name: cultural-data-update
        path: data/data_worldsurvey_valores.json
        retention-days: 7

    - name: Commit y push de datos actualizados
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/data_worldsurvey_valores.json
        git diff --staged --quiet || git commit -m "🤖 Actualizar datos culturales WVS [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notificar éxito
      if: success()
      run: |
        echo "🚀 Actualización cultural completada exitosamente!"
        echo "Archivo generado: data/data_worldsurvey_valores.json"

    - name: Notificar fallo
      if: failure()
      run: |
        echo "❌ La actualización cultural falló"
        exit 1
