# scripts/obtiene_historical_data_2020_2025.yml
name: Obtener Datos Históricos 2020-2025

description: |
  Script para obtener datos históricos del Banco Mundial y FMI
  para los años 2020-2025 y almacenarlos en un archivo JSON.

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 1 *'  # Ejecutar una vez al año el 1 de enero a las 2:00 AM
  push:
    branches: [ main ]
    paths:
      - 'scripts/obtiene_historical_data_2020_2025.py'

jobs:
  obtener-datos-historicos:
    name: Obtener Datos Históricos
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Instalar dependencias específicas
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.31.0 pandas==2.0.3 numpy==1.24.3
        echo "Dependencias instaladas:"
        pip list | grep -E "requests|pandas|numpy"

    - name: Verificar instalación de dependencias
      run: |
        echo "Verificando versión de requests:"
        python -c "import requests; print(f'Requests version: {requests.__version__}')"
        echo "Verificando versión de pandas:"
        python -c "import pandas as pd; print(f'Pandas version: {pd.__version__}')"
        echo "Verificando versión de numpy:"
        python -c "import numpy as np; print(f'Numpy version: {np.__version__}')"

    - name: Crear directorio de datos
      run: |
        mkdir -p data
        echo "Directorio data creado"

    - name: Ejecutar script de obtención de datos
      run: |
        python scripts/obtiene_historical_data_2020_2025.py
      env:
        PYTHONPATH: ${{ github.workspace }}
        MAX_RETRIES: 5
        REQUEST_TIMEOUT: 90
      timeout-minutes: 120  # Timeout extendido para las APIs

    - name: Verificar archivo generado
      run: |
        if [ -f "data/historical_data_2020_2025.json" ]; then
          echo "✅ Archivo histórico generado correctamente"
          ls -la data/historical_data_2020_2025.json
          echo "Tamaño del archivo: $(du -h data/historical_data_2020_2025.json | cut -f1)"
          echo "Estructura del archivo:"
          python -c "
          import json
          with open('data/historical_data_2020_2025.json', 'r') as f:
              data = json.load(f)
          print(f'Países en World Bank: {len(data.get(\"world_bank\", {}))}')
          print(f'Países en IMF: {len(data.get(\"imf\", {}))}')
          print(f'Fecha generación: {data.get(\"metadata\", {}).get(\"generated_on\")}')
          "
        else
          echo "❌ Error: No se generó el archivo histórico"
          exit 1
        fi

    - name: Validar estructura JSON
      run: |
        python -c "
        import json
        try:
            with open('data/historical_data_2020_2025.json', 'r') as f:
                data = json.load(f)
            print('✅ JSON válido')
            if 'world_bank' in data and 'imf' in data and 'metadata' in data:
                print('✅ Estructura correcta')
            else:
                print('❌ Estructura incorrecta')
                exit(1)
        except Exception as e:
            print(f'❌ Error en JSON: {e}')
            exit(1)
        "

    - name: Subir artefacto con datos históricos
      uses: actions/upload-artifact@v4
      with:
        name: historical-data-2020-2025
        path: data/historical_data_2020_2025.json
        retention-days: 7

    - name: Commit y push de datos actualizados
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/historical_data_2020_2025.json
        git diff --staged --quiet || git commit -m "🤖 Actualizar datos históricos 2020-2025 [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notificar éxito
      if: success()
      run: |
        echo "🚀 Proceso completado exitosamente!"
        echo "Archivo generado: data/historical_data_2020_2025.json"

    - name: Notificar fallo
      if: failure()
      run: |
        echo "❌ El proceso falló"
        exit 1
