name: Generate Cliodynamic Data

on:
  schedule:
    # Ejecutar diariamente a las 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Permite ejecución manual

jobs:
  generate-data:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas numpy requests

    - name: Generate CSV data
      run: |
        # Crear directorio data si no existe
        mkdir -p data
        # Ejecutar el script
        python scripts/generate_csv.py

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cliodynamic-data-$(date +%Y-%m-%d)
        path: data/combined_analysis_results.csv
